### ISSUE TITLE
🐛 nursery/useHooksAtTopLevel false positive

### ISSUE THREAD

**Issue by lu-zen** [rome/tools#4463]
### Environment information

```block
yarn run v1.22.19
$ project/node_modules/.bin/rome rage
CLI:
  Version:                      12.0.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         "xterm-kitty"
  JS_RUNTIME_VERSION:           "v18.16.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/1.22.19"

Rome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false

Workspace:
  Open Documents:               0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i The client isn't connected to any server but rage discovered this running Rome server.

Server:
  Version:                      12.0.0
  Name:                         rome_lsp
  CPU Architecture:             x86_64
  OS:                           linux

Workspace:
  Open Documents:               0

Other Active Server Workspaces:

Workspace:
  Open Documents:               1
  Client Name:                  Visual Studio Code
  Client Version:               1.77.1

Rome Server Log:

! Please review the content of the log file before sharing it publicly as it may contain sensitive information:
  * Path names that may reveal your name, a project name, or the name of your employer.
  * Source code

┐rome_cli::commands::daemon::Running Server{pid=40714}
├─┐rome_lsp::server::initialize{root_uri=file://project, capabilities=ClientCapabilities { workspace: Some(WorkspaceClientCapabilities { apply_edit: Some(true), workspace_edit: Some(WorkspaceEditClientCapabilities { document_changes: Some(true), resource_operations: Some([Create, Rename, Delete]), failure_handling: Some(TextOnlyTransactional), normalizes_line_endings: Some(true), change_annotation_support: Some(ChangeAnnotationWorkspaceEditClientCapabilities { groups_on_label: Some(true) }) }), did_change_configuration: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), did_change_watched_files: Some(DidChangeWatchedFilesClientCapabilities { dynamic_registration: Some(true), relative_pattern_support: Some(true) }), symbol: Some(WorkspaceSymbolClientCapabilities { dynamic_registration: Some(true), symbol_kind: Some(SymbolKindCapability { value_set: Some([File, Module, Namespace, Package, Class, Method, Property, Field, Constructor, Enum, Interface, Function, Variable, Constant, String, Number, Boolean, Array, Object, Key, Null, EnumMember, Struct, Event, Operator, TypeParameter]) }), tag_support: Some(TagSupport { value_set: [Deprecated] }), resolve_support: Some(WorkspaceSymbolResolveSupportCapability { properties: ["location.range"] }) }), execute_command: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), workspace_folders: Some(true), configuration: Some(true), semantic_tokens: Some(SemanticTokensWorkspaceClientCapabilities { refresh_support: Some(true) }), code_lens: Some(CodeLensWorkspaceClientCapabilities { refresh_support: Some(true) }), file_operations: Some(WorkspaceFileOperationsClientCapabilities { dynamic_registration: Some(true), did_create: Some(true), will_create: Some(true), did_rename: Some(true), will_rename: Some(true), did_delete: Some(true), will_delete: Some(true) }), inline_value: Some(InlineValueWorkspaceClientCapabilities { refresh_support: Some(true) }), inlay_hint: Some(InlayHintWorkspaceClientCapabilities { refresh_support: Some(true) }) }), text_document: Some(TextDocumentClientCapabilities { synchronization: Some(TextDocumentSyncClientCapabilities { dynamic_registration: Some(true), will_save: Some(true), will_save_wait_until: Some(true), did_save: Some(true) }), completion: Some(CompletionClientCapabilities { dynamic_registration: Some(true), completion_item: Some(CompletionItemCapability { snippet_support: Some(true), commit_characters_support: Some(true), documentation_format: Some([Markdown, PlainText]), deprecated_support: Some(true), preselect_support: Some(true), tag_support: Some(TagSupport { value_set: [Deprecated] }), insert_replace_support: Some(true), resolve_support: Some(CompletionItemCapabilityResolveSupport { properties: ["documentation", "detail", "additionalTextEdits"] }), insert_text_mode_support: Some(InsertTextModeSupport { value_set: [AsIs, AdjustIndentation] }), label_details_support: Some(true) }), completion_item_kind: Some(CompletionItemKindCapability { value_set: Some([Text, Method, Function, Constructor, Field, Variable, Class, Interface, Module, Property, Unit, Value, Enum, Keyword, Snippet, Color, File, Reference, Folder, EnumMember, Constant, Struct, Event, Operator, TypeParameter]) }), context_support: Some(true), insert_text_mode: Some(AdjustIndentation), completion_list: Some(CompletionListCapability { item_defaults: Some(["commitCharacters", "editRange", "insertTextFormat", "insertTextMode"]) }) }), hover: Some(HoverClientCapabilities { dynamic_registration: Some(true), content_format: Some([Markdown, PlainText]) }), signature_help: Some(SignatureHelpClientCapabilities { dynamic_registration: Some(true), signature_information: Some(SignatureInformationSettings { documentation_format: Some([Markdown, PlainText]), parameter_information: Some(ParameterInformationSettings { label_offset_support: Some(true) }), active_parameter_support: Some(true) }), context_support: Some(true) }), references: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), document_highlight: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), document_symbol: Some(DocumentSymbolClientCapabilities { dynamic_registration: Some(true), symbol_kind: Some(SymbolKindCapability { value_set: Some([File, Module, Namespace, Package, Class, Method, Property, Field, Constructor, Enum, Interface, Function, Variable, Constant, String, Number, Boolean, Array, Object, Key, Null, EnumMember, Struct, Event, Operator, TypeParameter]) }), hierarchical_document_symbol_support: Some(true), tag_support: Some(TagSupport { value_set: [Deprecated] }) }), formatting: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), range_formatting: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), on_type_formatting: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), declaration: Some(GotoCapability { dynamic_registration: Some(true), link_support: Some(true) }), definition: Some(GotoCapability { dynamic_registration: Some(true), link_support: Some(true) }), type_definition: Some(GotoCapability { dynamic_registration: Some(true), link_support: Some(true) }), implementation: Some(GotoCapability { dynamic_registration: Some(true), link_support: Some(true) }), code_action: Some(CodeActionClientCapabilities { dynamic_registration: Some(true), code_action_literal_support: Some(CodeActionLiteralSupport { code_action_kind: CodeActionKindLiteralSupport { value_set: ["", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports"] } }), is_preferred_support: Some(true), disabled_support: Some(true), data_support: Some(true), resolve_support: Some(CodeActionCapabilityResolveSupport { properties: ["edit"] }), honors_change_annotations: Some(false) }), code_lens: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), document_link: Some(DocumentLinkClientCapabilities { dynamic_registration: Some(true), tooltip_support: Some(true) }), color_provider: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), rename: Some(RenameClientCapabilities { dynamic_registration: Some(true), prepare_support: Some(true), prepare_support_default_behavior: Some(Identifier), honors_change_annotations: Some(true) }), publish_diagnostics: Some(PublishDiagnosticsClientCapabilities { related_information: Some(true), tag_support: Some(TagSupport { value_set: [Unnecessary, Deprecated] }), version_support: Some(false), code_description_support: Some(true), data_support: Some(true) }), folding_range: Some(FoldingRangeClientCapabilities { dynamic_registration: Some(true), range_limit: Some(5000), line_folding_only: Some(true), folding_range_kind: Some(FoldingRangeKindCapability { value_set: Some([Comment, Imports, Region]) }), folding_range: Some(FoldingRangeCapability { collapsed_text: Some(false) }) }), selection_range: Some(SelectionRangeClientCapabilities { dynamic_registration: Some(true) }), linked_editing_range: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), call_hierarchy: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), semantic_tokens: Some(SemanticTokensClientCapabilities { dynamic_registration: Some(true), requests: SemanticTokensClientCapabilitiesRequests { range: Some(true), full: Some(Delta { delta: Some(true) }) }, token_types: [SemanticTokenType("namespace"), SemanticTokenType("type"), SemanticTokenType("class"), SemanticTokenType("enum"), SemanticTokenType("interface"), SemanticTokenType("struct"), SemanticTokenType("typeParameter"), SemanticTokenType("parameter"), SemanticTokenType("variable"), SemanticTokenType("property"), SemanticTokenType("enumMember"), SemanticTokenType("event"), SemanticTokenType("function"), SemanticTokenType("method"), SemanticTokenType("macro"), SemanticTokenType("keyword"), SemanticTokenType("modifier"), SemanticTokenType("comment"), SemanticTokenType("string"), SemanticTokenType("number"), SemanticTokenType("regexp"), SemanticTokenType("operator"), SemanticTokenType("decorator")], token_modifiers: [SemanticTokenModifier("declaration"), SemanticTokenModifier("definition"), SemanticTokenModifier("readonly"), SemanticTokenModifier("static"), SemanticTokenModifier("deprecated"), SemanticTokenModifier("abstract"), SemanticTokenModifier("async"), SemanticTokenModifier("modification"), SemanticTokenModifier("documentation"), SemanticTokenModifier("defaultLibrary")], formats: [TokenFormat("relative")], overlapping_token_support: Some(false), multiline_token_support: Some(false), server_cancel_support: Some(true), augments_syntax_tokens: Some(true) }), moniker: None, type_hierarchy: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), inline_value: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), inlay_hint: Some(InlayHintClientCapabilities { dynamic_registration: Some(true), resolve_support: Some(InlayHintResolveClientCapabilities { properties: ["tooltip", "textEdits", "label.tooltip", "label.location", "label.command"] }) }) }), window: Some(WindowClientCapabilities { work_done_progress: Some(true), show_message: Some(ShowMessageRequestClientCapabilities { message_action_item: Some(MessageActionItemCapabilities { additional_properties_support: Some(true) }) }), show_document: Some(ShowDocumentClientCapabilities { support: true }) }), general: Some(GeneralClientCapabilities { regular_expressions: Some(RegularExpressionsClientCapabilities { engine: "ECMAScript", version: Some("ES2020") }), markdown: Some(MarkdownClientCapabilities { parser: "marked", version: Some("1.1.0"), allowed_tags: None }), stale_request_support: Some(StaleRequestSupportClientCapabilities { cancel: true, retry_on_content_modified: ["textDocument/semanticTokens/full", "textDocument/semanticTokens/range", "textDocument/semanticTokens/full/delta"] }), position_encodings: Some([PositionEncodingKind("utf-16")]) }), experimental: None }, client_info=ClientInfo { name: "Visual Studio Code", version: Some("1.77.1") }, root_path="project", workspace_folders=[WorkspaceFolder { uri: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "project", query: None, fragment: None }, name: "rome-bug" }]}
│ ├─0ms INFO rome_lsp::server Starting Rome Language Server...
│ ├─0ms WARN rome_lsp::server The Rome Server was initialized with the deprecated `root_path` parameter: this is not supported, use `root_uri` instead
│ ├─0ms WARN rome_lsp::server The Rome Server was initialized with the `workspace_folders` parameter: this is unsupported at the moment, use `root_uri` instead
├─┘
├─┐rome_lsp::server::initialized{params=InitializedParams}
│ ├─0ms INFO rome_lsp::server Attempting to load the configuration from 'rome.json' file
│ ├─┐rome_lsp::session::load_extension_settings{}
│ ├─┐rome_lsp::session::load_workspace_settings{}
│ │ ├─0ms INFO rome_service::configuration Attempting to read the configuration file from project/rome.json
│ │ ├─┐rome_fs::fs::os::OsFileSystem::open_with_options{path="project/rome.json", options=OpenOptions { read: true, write: false, truncate: false, create: false, create_new: false }}
│ │ ├─┘
│ │ ├─┐rome_fs::fs::os::OsFile::read_to_string{}
│ │ ├─┘
│ │ ├─┐rome_json_parser::parse{}
│ │ ├─┘
│ │ ├─0ms WARN rome_lsp::session The deserialization of the configuration resulted in errors. Rome will its defaults where possible.
│ │ ├─0ms INFO rome_lsp::session Loaded workspace settings: Configuration {
│ │ │     schema: Some(
│ │ │         "\"./node_modules/rome/configuration_schema.json\"",
│ │ │     ),
│ │ │     files: Some(
│ │ │         FilesConfiguration {
│ │ │             max_size: None,
│ │ │             ignore: Some(
│ │ │                 {
│ │ │                     "node_modules",
│ │ │                     "build",
│ │ │                     "build/public",
│ │ │                     ".env",
│ │ │                     "/app/main.css",
│ │ │                     "dbschema",
│ │ │                 },
│ │ │             ),
│ │ │         },
│ │ │     ),
│ │ │     formatter: Some(
│ │ │         FormatterConfiguration {
│ │ │             enabled: true,
│ │ │             format_with_errors: false,
│ │ │             indent_style: Space,
│ │ │             indent_size: 2,
│ │ │             line_width: LineWidth(
│ │ │                 80,
│ │ │             ),
│ │ │             ignore: None,
│ │ │         },
│ │ │     ),
│ │ │     organize_imports: Some(
│ │ │         OrganizeImports {
│ │ │             enabled: true,
│ │ │             ignore: None,
│ │ │         },
│ │ │     ),
│ │ │     linter: Some(
│ │ │         LinterConfiguration {
│ │ │             enabled: true,
│ │ │             rules: Some(
│ │ │                 Rules {
│ │ │                     recommended: Some(
│ │ │                         true,
│ │ │                     ),
│ │ │                     all: None,
│ │ │                     a11y: None,
│ │ │                     complexity: None,
│ │ │                     correctness: None,
│ │ │                     nursery: Some(
│ │ │                         Nursery {
│ │ │                             recommended: None,
│ │ │                             all: Some(
│ │ │                                 true,
│ │ │                             ),
│ │ │                             no_assign_in_expressions: None,
│ │ │                             no_banned_types: None,
│ │ │                             no_class_assign: None,
│ │ │                             no_comma_operator: None,
│ │ │                             no_confusing_labels: None,
│ │ │                             no_duplicate_case: None,
│ │ │                             no_duplicate_class_members: None,
│ │ │                             no_duplicate_jsx_props: None,
│ │ │                             no_extra_labels: None,
│ │ │                             no_extra_semicolons: None,
│ │ │                             no_global_object_calls: None,
│ │ │                             no_inferrable_types: None,
│ │ │                             no_inner_declarations: None,
│ │ │                             no_invalid_constructor_super: None,
│ │ │                             no_namespace: None,
│ │ │                             no_noninteractive_element_to_interactive_role: None,
│ │ │                             no_parameter_assign: None,
│ │ │                             no_parameter_properties: None,
│ │ │                             no_prototype_builtins: None,
│ │ │                             no_redeclare: None,
│ │ │                             no_redundant_alt: None,
│ │ │                             no_restricted_globals: None,
│ │ │                             no_self_assign: None,
│ │ │                             no_self_compare: None,
│ │ │                             no_svg_without_title: None,
│ │ │                             no_switch_declarations: None,
│ │ │                             no_unreachable_super: None,
│ │ │                             no_unsafe_optional_chaining: None,
│ │ │                             no_unused_labels: None,
│ │ │                             no_useless_catch: None,
│ │ │                             no_useless_rename: None,
│ │ │                             no_useless_switch_case: None,
│ │ │                             no_with: None,
│ │ │                             use_aria_prop_types: None,
│ │ │                             use_aria_props_for_role: None,
│ │ │                             use_camel_case: Some(
│ │ │                                 Plain(
│ │ │                                     Off,
│ │ │                                 ),
│ │ │                             ),
│ │ │                             use_exhaustive_dependencies: None,
│ │ │                             use_hook_at_top_level: None,
│ │ │                             use_iframe_title: None,
│ │ │                             use_is_nan: None,
│ │ │                             use_media_caption: None,
│ │ │                             use_namespace_keyword: None,
│ │ │                             use_valid_aria_props: None,
│ │ │                             use_valid_lang: None,
│ │ │                             use_yield: None,
│ │ │                         },
│ │ │                     ),
│ │ │                     performance: None,
│ │ │                     security: None,
│ │ │                     style: None,
│ │ │                     suspicious: None,
│ │ │                 },
│ │ │             ),
│ │ │             ignore: None,
│ │ │         },
│ │ │     ),
│ │ │     javascript: None,
│ │ │ }
│ │ ├─┐rome_service::workspace::server::update_settings{params=UpdateSettingsParams { configuration: Configuration { schema: Some("\"./node_modules/rome/configuration_schema.json\""), files: Some(FilesConfiguration { max_size: None, ignore: Some({"node_modules", "build", "build/public", ".env", "/app/main.css", "dbschema"}) }), formatter: Some(FormatterConfiguration { enabled: true, format_with_errors: false, indent_style: Space, indent_size: 2, line_width: LineWidth(80), ignore: None }), organize_imports: Some(OrganizeImports { enabled: true, ignore: None }), linter: Some(LinterConfiguration { enabled: true, rules: Some(Rules { recommended: Some(true), all: None, a11y: None, complexity: None, correctness: None, nursery: Some(Nursery { recommended: None, all: Some(true), no_assign_in_expressions: None, no_banned_types: None, no_class_assign: None, no_comma_operator: None, no_confusing_labels: None, no_duplicate_case: None, no_duplicate_class_members: None, no_duplicate_jsx_props: None, no_extra_labels: None, no_extra_semicolons: None, no_global_object_calls: None, no_inferrable_types: None, no_inner_declarations: None, no_invalid_constructor_super: None, no_namespace: None, no_noninteractive_element_to_interactive_role: None, no_parameter_assign: None, no_parameter_properties: None, no_prototype_builtins: None, no_redeclare: None, no_redundant_alt: None, no_restricted_globals: None, no_self_assign: None, no_self_compare: None, no_svg_without_title: None, no_switch_declarations: None, no_unreachable_super: None, no_unsafe_optional_chaining: None, no_unused_labels: None, no_useless_catch: None, no_useless_rename: None, no_useless_switch_case: None, no_with: None, use_aria_prop_types: None, use_aria_props_for_role: None, use_camel_case: Some(Plain(Off)), use_exhaustive_dependencies: None, use_hook_at_top_level: None, use_iframe_title: None, use_is_nan: None, use_media_caption: None, use_namespace_keyword: None, use_valid_aria_props: None, use_valid_lang: None, use_yield: None }), performance: None, security: None, style: None, suspicious: None }), ignore: None }), javascript: None } }}
│ │ │ ├─┐rome_service::settings::merge_with_configuration{configuration=Configuration { schema: Some("\"./node_modules/rome/configuration_schema.json\""), files: Some(FilesConfiguration { max_size: None, ignore: Some({"node_modules", "build", "build/public", ".env", "/app/main.css", "dbschema"}) }), formatter: Some(FormatterConfiguration { enabled: true, format_with_errors: false, indent_style: Space, indent_size: 2, line_width: LineWidth(80), ignore: None }), organize_imports: Some(OrganizeImports { enabled: true, ignore: None }), linter: Some(LinterConfiguration { enabled: true, rules: Some(Rules { recommended: Some(true), all: None, a11y: None, complexity: None, correctness: None, nursery: Some(Nursery { recommended: None, all: Some(true), no_assign_in_expressions: None, no_banned_types: None, no_class_assign: None, no_comma_operator: None, no_confusing_labels: None, no_duplicate_case: None, no_duplicate_class_members: None, no_duplicate_jsx_props: None, no_extra_labels: None, no_extra_semicolons: None, no_global_object_calls: None, no_inferrable_types: None, no_inner_declarations: None, no_invalid_constructor_super: None, no_namespace: None, no_noninteractive_element_to_interactive_role: None, no_parameter_assign: None, no_parameter_properties: None, no_prototype_builtins: None, no_redeclare: None, no_redundant_alt: None, no_restricted_globals: None, no_self_assign: None, no_self_compare: None, no_svg_without_title: None, no_switch_declarations: None, no_unreachable_super: None, no_unsafe_optional_chaining: None, no_unused_labels: None, no_useless_catch: None, no_useless_rename: None, no_useless_switch_case: None, no_with: None, use_aria_prop_types: None, use_aria_props_for_role: None, use_camel_case: Some(Plain(Off)), use_exhaustive_dependencies: None, use_hook_at_top_level: None, use_iframe_title: None, use_is_nan: None, use_media_caption: None, use_namespace_keyword: None, use_valid_aria_props: None, use_valid_lang: None, use_yield: None }), performance: None, security: None, style: None, suspicious: None }), ignore: None }), javascript: None }}
│ │ │ ├─┘
│ │ ├─┘
│ ├─┘
├─┐rome_lsp::handlers::text_document::did_open{params=DidOpenTextDocumentParams { text_document: TextDocumentItem { uri: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "project/index.js", query: None, fragment: None }, language_id: "javascript", version: 1, text: "import { useMemo } from \"react\";\n\nexport function useMatchesData(id) {\n  const matchingRoutes = [{ id: \"foo\", data: [] }];\n  const route = useMemo(\n    () => matchingRoutes.find((route) => route.id === id),\n    [id],\n  );\n  return route?.data;\n}\n\nexport const useRootData = () => {\n  const root = useMatchesData(\"root\");\n  return root;\n};\n" } }}
│ ├─┐rome_lsp::session::update_diagnostics{url=file://project/index.js}
│ │ ├─┐rome_js_parser::parse::parse{}
│ │ ├─┘
│ │ ├─0ms DEBUG rome_rowan::ast::batch pushing change...
│ ├─┘
├─┘
│ │ ├─2ms INFO rome_lsp::session Loaded client configuration: Object {
│ │ │     "lspBin": Null,
│ │ │     "rename": Null,
│ │ │     "requireConfiguration": Bool(false),
│ │ │ }
│ ├─┘
│ ├─4ms INFO rome_lsp::session Unregister capabilities "textDocument/rangeFormatting, textDocument/formatting, workspace/didChangeConfiguration, textDocument/onTypeFormatting, textDocument/rename, workspace/didChangeWatchedFiles"
│ ├─4ms INFO rome_lsp::session Register capabilities "textDocument/rangeFormatting, textDocument/formatting, workspace/didChangeConfiguration, textDocument/onTypeFormatting, workspace/didChangeWatchedFiles"
│ ├─┐rome_lsp::session::update_diagnostics{url=file://project/index.js}
│ │ ├─0ms DEBUG rome_rowan::ast::batch pushing change...
│ ├─┘
├─┘
├─┐rome_lsp::handlers::analysis::code_actions{uri=file://project/index.js, range=Range { start: Position { line: 0, character: 0 }, end: Position { line: 0, character: 0 } }, only=None, diagnostics=[]}
│ ├─0ms DEBUG rome_lsp::handlers::analysis Suggested actions: 
│ │ []
├─┘
├─┐rome_lsp::handlers::analysis::code_actions{uri=file://project/index.js, range=Range { start: Position { line: 11, character: 34 }, end: Position { line: 11, character: 34 } }, only=None, diagnostics=[]}
│ ├─0ms DEBUG rome_lsp::handlers::analysis Suggested actions: 
│ │ []
├─┘
├─┐rome_lsp::server::initialize{capabilities=ClientCapabilities { workspace: None, text_document: None, window: None, general: None, experimental: None }, client_info=ClientInfo { name: "rome_service", version: Some("12.0.0") }}
│ ├─0ms INFO rome_lsp::server Starting Rome Language Server...
├─┘
├─┐rome_lsp::server::rome/rage{params=RageParams}
├─┘

```

### What happened?

1. Given this code:
```jsx
// index.js
import { useMemo } from "react";

export function useMatchesData(id) {
  const matchingRoutes = [{ id: "foo", data: [] }];
  const route = useMemo(
    () => matchingRoutes.find((route) => route.id === id),
    [id],
  );
  return route?.data;
}

export const useRootData = () => {
  const root = useMatchesData("root");
  return root;
};

```
2. `rome check index.js` gives this output:
```
index.js:5:17 lint/nursery/useHookAtTopLevel ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⚠ This hook is being called indirectly and conditionally, but all hooks must be called in the exact same order in every component render.
  
    3 │ export function useMatchesData(id) {
    4 │   const matchingRoutes = [{ id: "foo", data: [] }];
  > 5 │   const route = useMemo(
      │                 ^^^^^^^
    6 │     () => matchingRoutes.find((route) => route.id === id),
    7 │     [id],
  
  ℹ This is the call path until the hook.
  
    12 │ export const useRootData = () => {
  > 13 │   const root = useMatchesData("root");
       │                ^^^^^^^^^^^^^^^^^^^^^^
    14 │   return root;
    15 │ };
  
  ℹ For React to preserve state between calls, hooks needs to be called unconditionally and always in the same order.
  
  ℹ See https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level
  
```

But useMemo is not being called conditionally.

### Expected result

No useHooksAtTopLevel error on line 5.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by nissy-dev** [comment]
@lu-zen Thank you for reporting! We have already noticed these false positives, and fixed in #4435
you could try the nightly version!

see: [playground](https://docs.rome.tools/playground/?lintRules=all&code=aQBtAHAAbwByAHQAIAB7ACAAdQBzAGUATQBlAG0AbwAgAH0AIABmAHIAbwBtACAAIgByAGUAYQBjAHQAIgA7AAoACgBlAHgAcABvAHIAdAAgAGYAdQBuAGMAdABpAG8AbgAgAHUAcwBlAE0AYQB0AGMAaABlAHMARABhAHQAYQAoAGkAZAApACAAewAKACAAIABjAG8AbgBzAHQAIABtAGEAdABjAGgAaQBuAGcAUgBvAHUAdABlAHMAIAA9ACAAWwB7ACAAaQBkADoAIAAiAGYAbwBvACIALAAgAGQAYQB0AGEAOgAgAFsAXQAgAH0AXQA7AAoAIAAgAGMAbwBuAHMAdAAgAHIAbwB1AHQAZQAgAD0AIAB1AHMAZQBNAGUAbQBvACgACgAgACAAIAAgACgAKQAgAD0APgAgAG0AYQB0AGMAaABpAG4AZwBSAG8AdQB0AGUAcwAuAGYAaQBuAGQAKAAoAHIAbwB1AHQAZQApACAAPQA%2BACAAcgBvAHUAdABlAC4AaQBkACAAPQA9AD0AIABpAGQAKQAsAAoAIAAgACAAIABbAGkAZABdACwACgAgACAAKQA7AAoAIAAgAHIAZQB0AHUAcgBuACAAcgBvAHUAdABlAD8ALgBkAGEAdABhADsACgB9AAoACgBlAHgAcABvAHIAdAAgAGMAbwBuAHMAdAAgAHUAcwBlAFIAbwBvAHQARABhAHQAYQAgAD0AIAAoACkAIAA9AD4AIAB7AAoAIAAgAGMAbwBuAHMAdAAgAHIAbwBvAHQAIAA9ACAAdQBzAGUATQBhAHQAYwBoAGUAcwBEAGEAdABhACgAIgByAG8AbwB0ACIAKQA7AAoAIAAgAHIAZQB0AHUAcgBuACAAcgBvAG8AdAA7AAoAfQA7AA%3D%3D)

**Comment by lu-zen** [comment]
@nissy-dev Thanks, it works fine for the previous snippet of code on nightly but still occurs for this:
```tsx
// index.ts

import { useMemo } from "react";

export function useMatchesData(id: string) {
  const matchingRoutes = [{ id: "foo", data: [] }];
  const route = useMemo(
    () => matchingRoutes.find((route) => route.id === id),
    [id],
  );
  return route?.data;
}

export function useOptionalUser() {
  const data = useMatchesData("root") as []; // asserting to something else causes the false positive
  if (!data) {
    return undefined;
  }
  return data;
}
```

`rome check` output:
```
index.ts:6:17 lint/nursery/useHookAtTopLevel ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⚠ This hook is being called indirectly and conditionally, but all hooks must be called in the exact same order in every component render.
  
    4 │ export function useMatchesData(id: string) {
    5 │   const matchingRoutes = [{ id: "foo", data: [] }];
  > 6 │   const route = useMemo(
      │                 ^^^^^^^
    7 │     () => matchingRoutes.find((route) => route.id === id),
    8 │     [id],
  
  ℹ This is the call path until the hook.
  
    13 │ export function useOptionalUser() {
  > 14 │   const data = useMatchesData("root") as []; // asserting to something causes the false positive
       │                ^^^^^^^^^^^^^^^^^^^^^^^
    15 │   if (!data) {
    16 │     return undefined;
  
  ℹ For React to preserve state between calls, hooks needs to be called unconditionally and always in the same order.
  
  ℹ See https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level
  

Checked 1 file(s) in 848µs
```

`rome rage`:
```
yarn run v1.22.19
$ sandbox/rome-bug/node_modules/.bin/rome rage
CLI:
  Version:                      12.0.0-nightly.b77547d
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  ROME_LOG_DIR:                 unset
  NO_COLOR:                     unset
  TERM:                         "xterm-kitty"
  JS_RUNTIME_VERSION:           "v18.16.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/1.22.19"

Rome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0

Discovering running Rome servers...

Running Rome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

i The client isn't connected to any server but rage discovered this running Rome server.

Server:
  Version:                      12.0.0-nightly.b77547d
  Name:                         rome_lsp
  CPU Architecture:             x86_64
  OS:                           linux

Workspace:
  Open Documents:               0

Other Active Server Workspaces:

Workspace:
  Open Documents:               1
  Client Name:                  Visual Studio Code
  Client Version:               1.77.1

Rome Server Log:

! Please review the content of the log file before sharing it publicly as it may contain sensitive information:
  * Path names that may reveal your name, a project name, or the name of your employer.
  * Source code

┐rome_cli::commands::daemon::Running Server{pid=22227}
├─┐rome_lsp::server::initialize{root_uri=file://sandbox/rome-bug, capabilities=ClientCapabilities { workspace: Some(WorkspaceClientCapabilities { apply_edit: Some(true), workspace_edit: Some(WorkspaceEditClientCapabilities { document_changes: Some(true), resource_operations: Some([Create, Rename, Delete]), failure_handling: Some(TextOnlyTransactional), normalizes_line_endings: Some(true), change_annotation_support: Some(ChangeAnnotationWorkspaceEditClientCapabilities { groups_on_label: Some(true) }) }), did_change_configuration: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), did_change_watched_files: Some(DidChangeWatchedFilesClientCapabilities { dynamic_registration: Some(true), relative_pattern_support: Some(true) }), symbol: Some(WorkspaceSymbolClientCapabilities { dynamic_registration: Some(true), symbol_kind: Some(SymbolKindCapability { value_set: Some([File, Module, Namespace, Package, Class, Method, Property, Field, Constructor, Enum, Interface, Function, Variable, Constant, String, Number, Boolean, Array, Object, Key, Null, EnumMember, Struct, Event, Operator, TypeParameter]) }), tag_support: Some(TagSupport { value_set: [Deprecated] }), resolve_support: Some(WorkspaceSymbolResolveSupportCapability { properties: ["location.range"] }) }), execute_command: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), workspace_folders: Some(true), configuration: Some(true), semantic_tokens: Some(SemanticTokensWorkspaceClientCapabilities { refresh_support: Some(true) }), code_lens: Some(CodeLensWorkspaceClientCapabilities { refresh_support: Some(true) }), file_operations: Some(WorkspaceFileOperationsClientCapabilities { dynamic_registration: Some(true), did_create: Some(true), will_create: Some(true), did_rename: Some(true), will_rename: Some(true), did_delete: Some(true), will_delete: Some(true) }), inline_value: Some(InlineValueWorkspaceClientCapabilities { refresh_support: Some(true) }), inlay_hint: Some(InlayHintWorkspaceClientCapabilities { refresh_support: Some(true) }) }), text_document: Some(TextDocumentClientCapabilities { synchronization: Some(TextDocumentSyncClientCapabilities { dynamic_registration: Some(true), will_save: Some(true), will_save_wait_until: Some(true), did_save: Some(true) }), completion: Some(CompletionClientCapabilities { dynamic_registration: Some(true), completion_item: Some(CompletionItemCapability { snippet_support: Some(true), commit_characters_support: Some(true), documentation_format: Some([Markdown, PlainText]), deprecated_support: Some(true), preselect_support: Some(true), tag_support: Some(TagSupport { value_set: [Deprecated] }), insert_replace_support: Some(true), resolve_support: Some(CompletionItemCapabilityResolveSupport { properties: ["documentation", "detail", "additionalTextEdits"] }), insert_text_mode_support: Some(InsertTextModeSupport { value_set: [AsIs, AdjustIndentation] }), label_details_support: Some(true) }), completion_item_kind: Some(CompletionItemKindCapability { value_set: Some([Text, Method, Function, Constructor, Field, Variable, Class, Interface, Module, Property, Unit, Value, Enum, Keyword, Snippet, Color, File, Reference, Folder, EnumMember, Constant, Struct, Event, Operator, TypeParameter]) }), context_support: Some(true), insert_text_mode: Some(AdjustIndentation), completion_list: Some(CompletionListCapability { item_defaults: Some(["commitCharacters", "editRange", "insertTextFormat", "insertTextMode"]) }) }), hover: Some(HoverClientCapabilities { dynamic_registration: Some(true), content_format: Some([Markdown, PlainText]) }), signature_help: Some(SignatureHelpClientCapabilities { dynamic_registration: Some(true), signature_information: Some(SignatureInformationSettings { documentation_format: Some([Markdown, PlainText]), parameter_information: Some(ParameterInformationSettings { label_offset_support: Some(true) }), active_parameter_support: Some(true) }), context_support: Some(true) }), references: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), document_highlight: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), document_symbol: Some(DocumentSymbolClientCapabilities { dynamic_registration: Some(true), symbol_kind: Some(SymbolKindCapability { value_set: Some([File, Module, Namespace, Package, Class, Method, Property, Field, Constructor, Enum, Interface, Function, Variable, Constant, String, Number, Boolean, Array, Object, Key, Null, EnumMember, Struct, Event, Operator, TypeParameter]) }), hierarchical_document_symbol_support: Some(true), tag_support: Some(TagSupport { value_set: [Deprecated] }) }), formatting: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), range_formatting: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), on_type_formatting: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), declaration: Some(GotoCapability { dynamic_registration: Some(true), link_support: Some(true) }), definition: Some(GotoCapability { dynamic_registration: Some(true), link_support: Some(true) }), type_definition: Some(GotoCapability { dynamic_registration: Some(true), link_support: Some(true) }), implementation: Some(GotoCapability { dynamic_registration: Some(true), link_support: Some(true) }), code_action: Some(CodeActionClientCapabilities { dynamic_registration: Some(true), code_action_literal_support: Some(CodeActionLiteralSupport { code_action_kind: CodeActionKindLiteralSupport { value_set: ["", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports"] } }), is_preferred_support: Some(true), disabled_support: Some(true), data_support: Some(true), resolve_support: Some(CodeActionCapabilityResolveSupport { properties: ["edit"] }), honors_change_annotations: Some(false) }), code_lens: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), document_link: Some(DocumentLinkClientCapabilities { dynamic_registration: Some(true), tooltip_support: Some(true) }), color_provider: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), rename: Some(RenameClientCapabilities { dynamic_registration: Some(true), prepare_support: Some(true), prepare_support_default_behavior: Some(Identifier), honors_change_annotations: Some(true) }), publish_diagnostics: Some(PublishDiagnosticsClientCapabilities { related_information: Some(true), tag_support: Some(TagSupport { value_set: [Unnecessary, Deprecated] }), version_support: Some(false), code_description_support: Some(true), data_support: Some(true) }), folding_range: Some(FoldingRangeClientCapabilities { dynamic_registration: Some(true), range_limit: Some(5000), line_folding_only: Some(true), folding_range_kind: Some(FoldingRangeKindCapability { value_set: Some([Comment, Imports, Region]) }), folding_range: Some(FoldingRangeCapability { collapsed_text: Some(false) }) }), selection_range: Some(SelectionRangeClientCapabilities { dynamic_registration: Some(true) }), linked_editing_range: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), call_hierarchy: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), semantic_tokens: Some(SemanticTokensClientCapabilities { dynamic_registration: Some(true), requests: SemanticTokensClientCapabilitiesRequests { range: Some(true), full: Some(Delta { delta: Some(true) }) }, token_types: [SemanticTokenType("namespace"), SemanticTokenType("type"), SemanticTokenType("class"), SemanticTokenType("enum"), SemanticTokenType("interface"), SemanticTokenType("struct"), SemanticTokenType("typeParameter"), SemanticTokenType("parameter"), SemanticTokenType("variable"), SemanticTokenType("property"), SemanticTokenType("enumMember"), SemanticTokenType("event"), SemanticTokenType("function"), SemanticTokenType("method"), SemanticTokenType("macro"), SemanticTokenType("keyword"), SemanticTokenType("modifier"), SemanticTokenType("comment"), SemanticTokenType("string"), SemanticTokenType("number"), SemanticTokenType("regexp"), SemanticTokenType("operator"), SemanticTokenType("decorator")], token_modifiers: [SemanticTokenModifier("declaration"), SemanticTokenModifier("definition"), SemanticTokenModifier("readonly"), SemanticTokenModifier("static"), SemanticTokenModifier("deprecated"), SemanticTokenModifier("abstract"), SemanticTokenModifier("async"), SemanticTokenModifier("modification"), SemanticTokenModifier("documentation"), SemanticTokenModifier("defaultLibrary")], formats: [TokenFormat("relative")], overlapping_token_support: Some(false), multiline_token_support: Some(false), server_cancel_support: Some(true), augments_syntax_tokens: Some(true) }), moniker: None, type_hierarchy: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), inline_value: Some(DynamicRegistrationClientCapabilities { dynamic_registration: Some(true) }), inlay_hint: Some(InlayHintClientCapabilities { dynamic_registration: Some(true), resolve_support: Some(InlayHintResolveClientCapabilities { properties: ["tooltip", "textEdits", "label.tooltip", "label.location", "label.command"] }) }) }), window: Some(WindowClientCapabilities { work_done_progress: Some(true), show_message: Some(ShowMessageRequestClientCapabilities { message_action_item: Some(MessageActionItemCapabilities { additional_properties_support: Some(true) }) }), show_document: Some(ShowDocumentClientCapabilities { support: true }) }), general: Some(GeneralClientCapabilities { regular_expressions: Some(RegularExpressionsClientCapabilities { engine: "ECMAScript", version: Some("ES2020") }), markdown: Some(MarkdownClientCapabilities { parser: "marked", version: Some("1.1.0"), allowed_tags: None }), stale_request_support: Some(StaleRequestSupportClientCapabilities { cancel: true, retry_on_content_modified: ["textDocument/semanticTokens/full", "textDocument/semanticTokens/range", "textDocument/semanticTokens/full/delta"] }), position_encodings: Some([PositionEncodingKind("utf-16")]) }), experimental: None }, client_info=ClientInfo { name: "Visual Studio Code", version: Some("1.77.1") }, root_path="sandbox/rome-bug", workspace_folders=[WorkspaceFolder { uri: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "sandbox/rome-bug", query: None, fragment: None }, name: "rome-bug" }]}
│ ├─0ms INFO rome_lsp::server Starting Rome Language Server...
│ ├─0ms WARN rome_lsp::server The Rome Server was initialized with the deprecated `root_path` parameter: this is not supported, use `root_uri` instead
│ ├─0ms WARN rome_lsp::server The Rome Server was initialized with the `workspace_folders` parameter: this is unsupported at the moment, use `root_uri` instead
├─┘
├─┐rome_lsp::server::initialized{params=InitializedParams}
│ ├─0ms INFO rome_lsp::server Attempting to load the configuration from 'rome.json' file
│ ├─┐rome_lsp::session::load_extension_settings{}
│ ├─┐rome_lsp::session::load_workspace_settings{}
│ │ ├─┐rome_fs::fs::os::OsFileSystem::open_with_options{path="sandbox/rome-bug/rome.json", options=OpenOptions { read: true, write: false, truncate: false, create: false, create_new: false }}
│ │ ├─┘
│ │ ├─┐rome_fs::fs::os::OsFile::read_to_string{}
│ │ ├─┘
│ │ ├─┐rome_json_parser::parse{}
│ │ ├─┘
│ │ ├─0ms WARN rome_lsp::session The deserialization of the configuration resulted in errors. Rome will its defaults where possible.
│ │ ├─0ms INFO rome_lsp::session Loaded workspace settings: Configuration {
│ │ │     schema: Some(
│ │ │         "./node_modules/rome/configuration_schema.json",
│ │ │     ),
│ │ │     vcs: None,
│ │ │     files: None,
│ │ │     formatter: Some(
│ │ │         FormatterConfiguration {
│ │ │             enabled: Some(
│ │ │                 true,
│ │ │             ),
│ │ │             format_with_errors: Some(
│ │ │                 false,
│ │ │             ),
│ │ │             indent_style: Some(
│ │ │                 Tab,
│ │ │             ),
│ │ │             indent_size: Some(
│ │ │                 2,
│ │ │             ),
│ │ │             line_width: Some(
│ │ │                 LineWidth(
│ │ │                     80,
│ │ │                 ),
│ │ │             ),
│ │ │             ignore: None,
│ │ │         },
│ │ │     ),
│ │ │     organize_imports: Some(
│ │ │         OrganizeImports {
│ │ │             enabled: Some(
│ │ │                 true,
│ │ │             ),
│ │ │             ignore: None,
│ │ │         },
│ │ │     ),
│ │ │     linter: Some(
│ │ │         LinterConfiguration {
│ │ │             enabled: Some(
│ │ │                 true,
│ │ │             ),
│ │ │             rules: Some(
│ │ │                 Rules {
│ │ │                     recommended: Some(
│ │ │                         true,
│ │ │                     ),
│ │ │                     all: Some(
│ │ │                         true,
│ │ │                     ),
│ │ │                     a11y: None,
│ │ │                     complexity: None,
│ │ │                     correctness: None,
│ │ │                     nursery: None,
│ │ │                     performance: None,
│ │ │                     security: None,
│ │ │                     style: None,
│ │ │                     suspicious: None,
│ │ │                 },
│ │ │             ),
│ │ │             ignore: None,
│ │ │         },
│ │ │     ),
│ │ │     javascript: None,
│ │ │ }
│ │ ├─┐rome_service::workspace::server::update_settings{params=UpdateSettingsParams { configuration: Configuration { schema: Some("./node_modules/rome/configuration_schema.json"), vcs: None, files: None, formatter: Some(FormatterConfiguration { enabled: Some(true), format_with_errors: Some(false), indent_style: Some(Tab), indent_size: Some(2), line_width: Some(LineWidth(80)), ignore: None }), organize_imports: Some(OrganizeImports { enabled: Some(true), ignore: None }), linter: Some(LinterConfiguration { enabled: Some(true), rules: Some(Rules { recommended: Some(true), all: Some(true), a11y: None, complexity: None, correctness: None, nursery: None, performance: None, security: None, style: None, suspicious: None }), ignore: None }), javascript: None } }}
│ │ │ ├─┐rome_service::settings::merge_with_configuration{configuration=Configuration { schema: Some("./node_modules/rome/configuration_schema.json"), vcs: None, files: None, formatter: Some(FormatterConfiguration { enabled: Some(true), format_with_errors: Some(false), indent_style: Some(Tab), indent_size: Some(2), line_width: Some(LineWidth(80)), ignore: None }), organize_imports: Some(OrganizeImports { enabled: Some(true), ignore: None }), linter: Some(LinterConfiguration { enabled: Some(true), rules: Some(Rules { recommended: Some(true), all: Some(true), a11y: None, complexity: None, correctness: None, nursery: None, performance: None, security: None, style: None, suspicious: None }), ignore: None }), javascript: None }}
│ │ │ ├─┘
│ │ ├─┘
│ ├─┘
├─┐rome_lsp::handlers::text_document::did_open{params=DidOpenTextDocumentParams { text_document: TextDocumentItem { uri: Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "sandbox/rome-bug/index.ts", query: None, fragment: None }, language_id: "typescript", version: 1, text: "\nimport { useMemo } from \"react\";\n\nexport function useMatchesData(id: string) {\n  const matchingRoutes = [{ id: \"foo\", data: [] }];\n  const route = useMemo(\n    () => matchingRoutes.find((route) => route.id === id),\n    [id],\n  );\n  return route?.data;\n}\n\nexport function useOptionalUser() {\n  const data = useMatchesData(\"root\") as []; // asserting to something causes the false positive\n  if (!data) {\n    return undefined;\n  }\n  return data;\n}\n" } }}
│ ├─┐rome_lsp::session::update_diagnostics{url=file://sandbox/rome-bug/index.ts}
│ │ ├─┐rome_js_parser::parse::parse{}
│ │ ├─┘
│ │ ├─0ms DEBUG rome_rowan::ast::batch pushing change...
│ ├─┘
├─┘
│ │ ├─1ms INFO rome_lsp::session Loaded client configuration: Object {
│ │ │     "lspBin": Null,
│ │ │     "rename": Null,
│ │ │     "requireConfiguration": Bool(false),
│ │ │ }
│ ├─┘
│ ├─3ms INFO rome_lsp::session Unregister capabilities "textDocument/onTypeFormatting, textDocument/rename, workspace/didChangeConfiguration, workspace/didChangeWatchedFiles, textDocument/rangeFormatting, textDocument/formatting"
│ ├─4ms INFO rome_lsp::session Register capabilities "textDocument/onTypeFormatting, workspace/didChangeConfiguration, workspace/didChangeWatchedFiles, textDocument/rangeFormatting, textDocument/formatting"
│ ├─┐rome_lsp::session::update_diagnostics{url=file://sandbox/rome-bug/index.ts}
│ │ ├─0ms DEBUG rome_rowan::ast::batch pushing change...
│ ├─┘
├─┘
├─┐rome_lsp::server::initialize{capabilities=ClientCapabilities { workspace: None, text_document: None, window: None, general: None, experimental: None }, client_info=ClientInfo { name: "rome_service", version: Some("12.0.0-nightly.b77547d") }}
│ ├─0ms INFO rome_lsp::server Starting Rome Language Server...
├─┘
├─┐rome_lsp::server::rome/rage{params=RageParams}
├─┘

Done in 0.05s.
```

I noticed that removing the assertion makes the error go away '-'

**Comment by nissy-dev** [comment]
@lu-zen Good catch! I'll try to fix.
