### ISSUE TITLE
🐛 `package.json` race condition results in duplicate package warning

### ISSUE THREAD

**Issue by yassere** [rome/tools#955]
## Environment

<details>
<summary>$ npx rome rage --summary</summary>

```
Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    PATH: "/Users/Yasser/Dev/Test/TestRome/test-rome/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Yasser/bin:/Users/Yasser/bin"
    TERM: "xterm-256color"
    TERM_PROGRAM: "vscode"
    USER: "Yasser"
  }

User Config
  unset

Rome Version
  0.0.33

Node Version
  14.6.0

Platform
  darwin x64 19.5.0

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 24
    columns: 157
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/Users/Yasser/Dev/Test/TestRome/test-rome"
    realCwd: "/Users/Yasser/Dev/Test/TestRome/test-rome"
    silent: false
  }

Server Status
  Object {
    projects: Array [
      Object {id: 0}
      Object {id: 1}
    ]
    server: Object {
      heapTotal: 37_175_296
      pid: 48_462
      uptime: 0.335858216
    }
    workers: Array [
      Object {
        astCacheSize: 0
        heapTotal: 37_175_296
        ownedBytes: 0
        ownedFileCount: 0
        pid: 48_462
        uptime: 0.3357401
      }
    ]
  }
```
</details>

## Steps To Reproduce

```
$ mkdir test-rome && cd test-rome

$ npm init -y

$ npm install rome

$ git init

$ git add -A && git commit -m "Init"

$ npx rome init
```

Results in either:
<details>
<summary>nameCollision</summary>

```
Yassers-MBP:test-rome Yasser$ npx rome init

 Welcome to Rome! Let's get you started... 

[1/2] Generating lint config and apply formatting
✖ Generated diagnostics without a current request

 ~/Dev/Test/TestRome/test-rome/package.json:2:10 projectManager/nameCollision ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Duplicate package name test-rome

    1 │ {
  > 2 │   "name": "test-rome",
      │            ^^^^^^^^^
    3 │   "version": "1.0.0",
    4 │   "description": "",

  ℹ Defined already by ~/Dev/Test/TestRome/test-rome/package.json

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ℹ 3 files saved
  ✔ No problems found!

 Files created ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  - .config/rome.rjson: Your project configuration. Documentation: https://romefrontend.dev/#project-configuration
  - .editorconfig: Sets editor formatting and indentation options. Documentation: https://editorconfig.org/

 What next? ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  1. Setup an editor extension
     Get live errors as you type and format when you save. Learn more: https://romefrontend.dev/#editor-integration

  2. Try a command
     rome check is used to validate your code, verify formatting, and check for lint errors. Run rome --help for a full list of commands and flags.

  3. Read documentation
     Our website serves as a comprehensive source of guides and documentation https://romefrontend.dev/

  4. Get involved in the community
     Ask questions, get support, or contribute by participating on GitHub (https://github.com/romefrontend/rome) or our community Discord (
     https://discord.gg/rome)
```
</details>

or sometimes:

<details>
<summary>internalError</summary>

```
Yassers-MBP:test-rome Yasser$ npx rome init

 Welcome to Rome! Let's get you started... 

[1/2] Generating lint config and apply formatting

 project-rome/@internal/core/worker/Worker.ts:138:9 internalError/request ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Requested manifest 3 but we don't have it

   5. ___R$project$rome$$internal$core$worker$Worker_ts$default.getPartialManifest (project-rome/@internal/core/worker/Worker.ts:138:9)
   6. ___R$project$rome$$internal$core$worker$Worker_ts$default.parse (project-rome/@internal/core/worker/Worker.ts:435:26)
   7. parse (project-rome/@internal/core/worker/WorkerAPI.ts:238:15)
   8. ___R$project$rome$$internal$diagnostics$wrap_ts$catchDiagnostics (project-rome/@internal/diagnostics/wrap.ts:29:22)
   9. ___R$project$rome$$internal$core$worker$WorkerAPI_ts$default.analyzeDependencies (project-rome/@internal/core/worker/WorkerAPI.ts:237:28)
  10. analyzeDependencies (project-rome/@internal/core/worker/Worker.ts:219:19)
  11. ___R$project$rome$$internal$events$BridgeEvent_ts$default.call (project-rome/@internal/events/Event.ts:75:4)
  12. ___R$project$rome$$internal$events$BridgeEvent_ts$default.dispatchRequest (project-rome/@internal/events/BridgeEvent.ts:97:15)
  13. ___R$project$rome$$internal$core$common$bridges$WorkerBridge_ts$default.handleMessageRequest (project-rome/@internal/events/Bridge.ts:513:16)
  14. ___R$project$rome$$internal$core$common$bridges$WorkerBridge_ts$default.handleMessage (project-rome/@internal/events/Bridge.ts:463:9)
  15. Object.sendMessage (project-rome/@internal/events/bridgeCreators.ts:202:10)
  16. ___R$project$rome$$internal$core$common$bridges$WorkerBridge_ts$default.sendMessage (project-rome/@internal/events/Bridge.ts:426:7)
  17. sendMessage (project-rome/@internal/events/BridgeEvent.ts:203:15)
  18. new Promise
  19. ___R$project$rome$$internal$events$BridgeEvent_ts$default.call (project-rome/@internal/events/BridgeEvent.ts:162:9)
  20. call (project-rome/@internal/core/server/ServerRequest.ts:1068:47)
  21. ___R$project$rome$$internal$core$server$ServerRequest_ts$default.wrapRequestDiagnostic (project-rome/@internal/core/server/ServerRequest.ts:809:24)
  22. ___R$project$rome$$internal$core$server$ServerRequest_ts$default.requestWorkerAnalyzeDependencies (
      project-rome/@internal/core/server/ServerRequest.ts:1065:14)
  23. ___R$project$rome$$internal$core$server$dependencies$DependencyGraph_ts$default.resolve (
      project-rome/@internal/core/server/dependencies/DependencyGraph.ts:324:9)
  24. Function.allowMissing (project-rome/@internal/core/common/FileNotFound.ts:48:11)
  and 4 others...

  ℹ Error occurred while requesting analyzeDependencies for .config/rome.rjson

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
</details>

## Expected Results

Rome should initialize with no errors.

**Comment by sebmck** [comment]
Noticed this too. Race condition when the `package.json` file is formatted, saved, and then the project evicted and reloaded.

**Comment by sebmck** [comment]
Fixed by #957.

**Comment by yassere** [comment]
I'm still getting the `projectManager/nameCollision` error any time I `npx rome init`, even in a new project.

<details>
<summary>Error</summary>

```
Yassers-MBP:test Yasser$ npx rome init

 Welcome to Rome! Let's get you started... 

[1/2] Generating lint config and apply formatting
✖ Generated diagnostics without a current request

 ~/Dev/Test/TestRome/test/package.json:2:10 projectManager/nameCollision ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Duplicate package name test

    1 │ {
  > 2 │   "name": "test",
      │            ^^^^
    3 │   "version": "1.0.0",
    4 │   "description": "",

  ℹ Defined already by ~/Dev/Test/TestRome/test/package.json

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ℹ 2 files saved
  ✔ No problems found!

```

**Comment by ematipico** [comment]
I can confirm I get the same error too

**Comment by sebmck** [comment]
I don't think I'll have time to fix this before launch, so I'll look into it after. This doesn't cause any failures so should be fine. `rome init` is no longer destructive so it shouldn't matter. This is a race condition whenever we save `package.json` files.

**Comment by ematipico** [comment]
I think we can close it. It's not happening anymore.
